# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Jesse Pound"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Jesse Pound is an entrepreneur, engineer, and environmentalist. She is the co-founder of Vunatec where she is working to support smallholder Kenyan farmers to prevent post-harvest food waste and maximize their income."


# The subpath of your site, e.g. /blog, for generating urls
baseurl: 
# baseurl: https://jessepound

navigation:
- text: Home
  url: /#home
- text: about
  url: /#about
- text: portfolio
  url: /#portfolio
- text: Contact
  url: /#contact

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://jessepound.com"

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "JESSE POUND"

# Social links in the site footer
twitter_username: "username"
facebook_username: "username"
googleplus_username: "+username"
pinterest_username: "username"
linkedin_username: "username"
